force-app/main/default/objects/ProcessLog__c/ProcessLog__c.object-meta.xml
<CustomObject>
    <label>Process Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessLog__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/InternalError__c.field-meta.xml
<CustomField>
    <fullName>InternalError__c</fullName>
    <label>Erro interno</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <label>Nome do processo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>ID do registro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Requisição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/RequestDirection__c.field-meta.xml
<CustomField>
    <fullName>RequestDirection__c</fullName>
    <label>Direção da requisição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>OUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Resposta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/ProcessLogRecords__e.object-meta.xml
<CustomObject>
    <label>Registro de Process Log</label>
    <pluralLabel>Registros de Process Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProcessLogRecords__e/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/InternalError__c.field-meta.xml
<CustomField>
    <fullName>InternalError__c</fullName>
    <label>Erro interno</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <label>Nome do processo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>ID do registro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Requisição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/RequestDirection__c.field-meta.xml
<CustomField>
    <fullName>RequestDirection__c</fullName>
    <label>Direção da requisição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Resposta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessLogRecords__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/process_log/PL_ProcessLogBO.cls
public with sharing class PL_ProcessLogBO {
    
    private static final PL_ProcessLogBO instance = new PL_ProcessLogBO();

    public static PL_ProcessLogBO getInstance() {
        return instance;
    }

    public void createProcessLogRecord(List<ProcessLogRecords__e> listLogs){

        List<ProcessLog__c> listProcessLog = new List<ProcessLog__c>();

        for (ProcessLogRecords__e logRecord : listLogs) {
            listProcessLog.add(this.parseProcessLogFromProcessLogRecord(logRecord));
        }

        if (!listProcessLog.isEmpty()) insert listProcessLog;
    }

    private ProcessLog__c parseProcessLogFromProcessLogRecord(ProcessLogRecords__e logRecord){
        return new ProcessLog__c(
            RequestDirection__c = logRecord.RequestDirection__c,
            Endpoint__c = logRecord.Endpoint__c,
            InternalError__c = logRecord.InternalError__c,
            Header__c = logRecord.Header__c,
            RecordId__c = logRecord.RecordId__c,
            Method__c = logRecord.Method__c,
            ProcessName__c = logRecord.ProcessName__c,
            Request__c = logRecord.Request__c,
            Response__c = logRecord.Response__c,
            StatusCode__c = logRecord.StatusCode__c,
            Type__c = logRecord.Type__c
        );
    }
}